/**
 * Contract ABIs for Bio-Vault Protocol.
 *
 * These MUST match the deployed Solidity contracts in smart-contracts/contracts/.
 * If you change a contract, re-run `npx hardhat compile` and update these ABIs
 * to match, or regenerate from artifacts/contracts/<Name>.sol/<Name>.json.
 *
 * Last synced with:
 *   - MediaAnchor.sol   (pragma ^0.8.20)
 *   - AuthenticityToken.sol (pragma ^0.8.20)
 */

// ============================================================================
// MediaAnchor.sol
// ============================================================================
const MEDIA_ANCHOR_ABI = [
    // ── Write ────────────────────────────────────────────────────────────
    "function anchorMedia(string _mediaHash, string _bioSignature, string _hardwareID, address[] _consensusParties, string _ipfsHash, string _proofOfRealityHash, string _proofOfRealityIPFS, bool _allUniqueSignals, uint8 _detectedFaces) external",
    "function disputeMedia(string _mediaHash, string _reason) external",
    "function revokeMedia(string _mediaHash) external",

    // ── Read ─────────────────────────────────────────────────────────────
    "function verifyMedia(string _mediaHash) external view returns (bool exists, bool isValid, uint256 timestamp)",
    "function getMediaRecord(string _mediaHash) external view returns (tuple(string mediaHash, string bioSignature, string hardwareID, uint256 timestamp, address creator, address[] consensusParties, bool isRevoked, string ipfsHash, uint8 status, string proofOfRealityHash, string proofOfRealityIPFS, bool allUniqueSignals, uint8 detectedFaces))",
    "function getCreatorMedia(address _creator) external view returns (string[])",
    "function getParticipantMedia(address _participant) external view returns (string[])",
    "function getDisputes(string _mediaHash) external view returns (tuple(address disputer, string reason, uint256 timestamp, bool resolved)[])",
    "function hasConsent(string _mediaHash, address _address) external view returns (bool)",

    // ── Events ───────────────────────────────────────────────────────────
    "event MediaAnchored(string indexed mediaHash, address indexed creator, uint256 timestamp, string hardwareID, bool allUniqueSignals, uint8 detectedFaces)",
    "event ConsentAdded(string indexed mediaHash, address indexed participant, uint256 timestamp)",
    "event MediaDisputed(string indexed mediaHash, address indexed disputer, string reason, uint256 timestamp)",
    "event MediaRevoked(string indexed mediaHash, address indexed revoker, uint256 timestamp)"
];

// ============================================================================
// AuthenticityToken.sol  (Soulbound ERC-721)
// ============================================================================
const AUTHENTICITY_TOKEN_ABI = [
    // ── Write ────────────────────────────────────────────────────────────
    "function mint(address _to, string _mediaHash, string _bioSignature, string _hardwareID, string _ipfsHash) external returns (uint256)",

    // ── Read ─────────────────────────────────────────────────────────────
    "function tokenURI(uint256 tokenId) external view returns (string)",
    "function ownerOf(uint256 tokenId) external view returns (address)",
    "function balanceOf(address owner) external view returns (uint256)",
    "function getTokenByMediaHash(string _mediaHash) external view returns (uint256)",
    "function exists(string _mediaHash) external view returns (bool)",
    "function tokenAnchors(uint256 tokenId) external view returns (string mediaHash, string bioSignature, string hardwareID, uint256 timestamp, string ipfsHash)",
    "function mediaHashToToken(string) external view returns (uint256)",
    "function isSoulbound(uint256 tokenId) external view returns (bool)",

    // ── Events ───────────────────────────────────────────────────────────
    "event AuthenticityMinted(uint256 indexed tokenId, string indexed mediaHash, address indexed recipient, string bioSignature, string hardwareID, uint256 timestamp)",
    "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
];

// ============================================================================
// Groth16Verifier (generated by snarkjs from Circom circuit)
// ============================================================================
const GROTH16_VERIFIER_ABI = [
    "function verifyProof(uint[2] a, uint[2][2] b, uint[2] c, uint[] input) external view returns (bool)"
];

module.exports = {
    MEDIA_ANCHOR_ABI,
    AUTHENTICITY_TOKEN_ABI,
    GROTH16_VERIFIER_ABI
};
